### ISSUE TITLE
[ERROR] Library returns errors when installed

### ISSUE THREAD

**Issue by RichardB01** [FOSSASystems/FOSSA-Comms#1]
> In file included from .../Arduino/libraries/FOSSA-Comms/examples/PingPong/PingPong.ino:2:0:
> .../Arduino/libraries/FOSSA-Comms/src/FOSSA-Comms.h:5:10: fatal error: AESLib.h: No such file or directory
>  #include <AESLib.h>

**Comment by jgromes** [comment]
You're missing AESLib, it's one of the dependencies: https://github.com/DavyLandman/AESLib

**Comment by RichardB01** [comment]
> You're missing AESLib, it's one of the dependencies: https://github.com/DavyLandman/AESLib

can we bundle this library with the fossa-comms library so they both install at once?

**Comment by jgromes** [comment]
I'd rather not - future version of this library won't be using AESLib.
