### ISSUE TITLE
Complation Issues

### ISSUE THREAD

**Issue by Securethingsuk** [FOSSASystems/FOSSA-Comms#2]
I have looked to use this code on the stated UNO platform with SX1278. Ideally  but just does not compile .I wanted to use on  ESP 32 Heltec V2 Board as has display does not complie in that enviroment  as well and get issues with AESLib on both. See below, when trying to compile In Arduino IDE and In both cases get the same issues. Are these known  issues ?.

 Also is there a forum for discussion  on the issues  and no dobt others as there will be  I suspect be a lot once Fossa Sat1 Launches in the next few days.

Simon G8HAM

Multiple libraries were found for "FOSSA-Comms.h"
In file included from C:\Users\User\Documents\Arduino\libraries\AESLib-master\aes_dec-asm_faster.S:28:0:

 Used: C:\Users\User\Documents\Arduino\libraries\FOSSA-Comms-master
C:\Users\User\Documents\Arduino\libraries\AESLib-master\avr-asm-macros.S:31:20: fatal error: avr/io.h: No such file or directory

Multiple libraries were found for "AESLib.h"
compilation terminated.

**Comment by jgromes** [comment]
First of all, you seem to have installed FOSSA-Comms and AESLib more than once. Please only keep one library for each and delete the duplicates.

Second, FOSSA-Comms 1.0.0 depends on AESLib, which only works on AVR platform. Because of that, ESP32 is unsupported at the moment. AESLib will most likely be replaced by [tiny-AES-c](https://github.com/kokke/tiny-AES-c) in the near future, which is platform-agnostic and should work on ESP32.

**Comment by Securethingsuk** [comment]
Hi, Thanks for the   fast response. 

I noted the  issues on the multiple library’s but in the library folder I have only one copy of each of the specified   library folder. I will have to hunt down where they are coming from ? the  Board managers install?

OK on the fact  AESLib Library only works on AVR. I will look at tiny_AESLib as I would be good to get working on ESP32 as some nice boards for that such as the Heltec ESP32V2.
I am also going to look at the CubeCell  433MHz module as that has some interesting features as it integrates PS4000  with SX126x in one package   and works very well on LoRa Networks.

Looking forward to successful launch  of Fossa SAT1

Simon

Sent from Mail for Windows 10

**Comment by jgromes** [comment]
I changed the AES library to use our fork of [tiny-AES-c](https://github.com/FOSSASystems/tiny-AES-c), FOSSA-Comms should now work on almost any platform, including ESP32.

Regarding your problem with multiple libraries - it's not a matter of duplicate folders, rather duplicate .h files with the same name. I suggest you search your PC for FOSSA-Comms.h and AESLib.h to make sure you only have one of each.

**Comment by Securethingsuk** [comment]
Hi Many thanks for the updated  fork. I will try it in the next day or so. 

 

On the extra files I have found them after some searching . Thanks 

 Simon
